### ISSUE TITLE
Assumption on VCF file ending does not apply

### ISSUE THREAD

**Issue by christopher-mohr** [Boehringer-Ingelheim/Personalis-io#7]
We made the assumption that only VCF files of type "DNA" and "tumor" are gzipped as implemented here

https://github.com/Boehringer-Ingelheim/Personalis-io/blob/516135fc638a25adefef73236858012e6bd05be9/R/personalis.R#L444

This does not apply or has been changed in the reporting and leads to an error when reading a Personalis dataset with `read_vcf_data = TRUE`.  It looks like that usually "RNA" variants are not gzipped. 

I will try to confirm this and make a PR.

**Comment by grst** [comment]
This might actually be different between datasets. Probably safest ist to try `.vcf.gz` and fallback to `.vcf` in both cases.
